import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { ViewTransitions } from 'next-view-transitions';
import NextTopLoader from 'nextjs-toploader';
import { NextUIProvider } from '@nextui-org/react';

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Amazon Hackon',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <NextTopLoader showSpinner={false} color='#036ffc' />
        <NextUIProvider>
          <ViewTransitions>{children}</ViewTransitions>
        </NextUIProvider>
      </body>
    </html>
  );
}
